#!/usr/bin/env bash

echo '{ "lines": [ "hello","world" ], "message": "lorem ipsum dolor sit amet", "prompt": "test prompt"}'

# END TEST SCRIPT
cd "$(dirname "${BASH_SOURCE[0]}")"
sleep 0.1
magick import -window root "./result-screenshot-1.png" >&2
sleep 0.1

