#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"
rm result-text-1.txt

echo '{ "lines": [ "hello","world", "lorem", "ipsum", "lor" ], "message": "lorem ipsum dolor sit amet", "prompt": "test prompt", "input action": "send"}'


sleep 0.1;
import -window root "./result-screenshot-1.png" >&2


xdotool type lor

while IFS= read -t 0.1 -r line; do
  printf '%s\n' "$line" >> result-text-1.txt
done

# END TEST SCRIPT
sleep 0.1
import -window root "./result-screenshot-2.png" >&2
sleep 0.1

